[build]
builder = "NIXPACKS"
buildCommand = "python -m pip install --upgrade pip && pip install -r requirements.txt"
buildTimeout = 1800  # 30分钟
cache = true

[deploy]
startCommand = "gunicorn server:app --bind=0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[service]
port = "$PORT"

[build.env]
PYTHON_VERSION = "3.9"
PIP_DISABLE_PIP_VERSION_CHECK = "1"
PIP_DEFAULT_TIMEOUT = "100"
PORT = "8080" 